# Whenever we have a prerelease, we want to:
# * Build the sdist and attach it to the release.
# * Ensure that the docs will build.
# This should be triggered from the cmdline with `just prerelease`.
# Could also be triggered from the release page.
name: on-prerelease
on:
  release:
    types: [prereleased]
permissions:
  contents: write
jobs:
  build-sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Build the sdist"
        run: |
          python -m pip install build
          python -m build -s
      - name: "Attach build dist release with gh cli"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} dist/*.tar.gz

  ensure-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Install dependancies"
        run: python -m pip install -e ".[dev]"
      - name: "Build Docs"
        run: mkdocs build --clean --strict

  # Create and attach the changelog with commitizen
  create-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: "Generate changelog and push"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m pip install commitizen
          changelog="$(cz changelog --dry-run "v$(cz version --project)"))"
          gh release edit -n "$changelog"
